# Workflow de Integração Contínua (CI) focado na execução de testes unitários com Vitest
# Estrutura modular preparada para expansão futura (ex: inclusão de novos jobs como lint, build e e2e)

name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '24'
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TESTDINO_TOKEN: ${{ secrets.TESTDINO_TOKEN }}


jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v7

      # 2. Configuração do ambiente Node.js utilizando a versão global
      - name: Setup Node.js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Habilitação do Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable

      # 4. Instalação das dependências do projeto
      - name: Install dependencies
        run: yarn install

      # 5. Execução da suíte de testes unitários
      - name: Run unit tests
        run: yarn test
  build-and-deploy:
    name: Build and Deploy Vercel Preview
    needs: [unit-tests]
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.deploy.outputs.deployment-url }}

    steps:
      # 1. Checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v7
      # 2. Configuração do ambiente Node.js utilizando a versão global
      - name: Setup Node.js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      # 3. Habilitação do Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable
      # 4. Instalação das dependências do projeto
      - name: Install dependencies
        run: yarn install
      # 5. Obter as configurações do Vercel
      - name: Pull Vercel Configuration
        run: yarn vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}} --debug

      # 6. Build para o Vercel
      - name: Build for Vercel
        run: yarn vercel build --token=${{secrets.VERCEL_TOKEN}}

      # 7. Deploy preview no Vercel
      - name: Deploy preview
        id: deploy
        run: |
          URL=$(yarn --silent vercel deploy --prebuilt --target=preview --token=${{secrets.VERCEL_TOKEN}})
          echo "deployment-url=$URL" >> $GITHUB_OUTPUT
    



  e2e-tests:
    name: Run E2E Tests
    needs: [build-and-deploy]
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v7

      # 2. Configuração do ambiente Node.js utilizando a versão global
      - name: Setup Node.js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Habilitação do Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable

      # 4. Instalação das dependências do projeto
      - name: Install dependencies
        run: yarn install

      # 5- Instalação do Chromium
      - name: Install Playwright Browser
        run: yarn playwright install --with-deps chromium
      
      # 6. Execução dos testes de regressão 
      - name: Run E2E Regression Tests
        run: yarn playwright test
        env: 
          BASE_URL: ${{ needs.build-and-deploy.outputs.deployment-url }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # 7. Relatório de Testes Automatizados
      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      # 8. Report Test Dino
      - name: Publish TestDino Report
        if: ${{ !cancelled() }}
        run: npx tdpw upload ./playwright-report --token=${{ secrets.TESTDINO_TOKEN }}

  promote:
    name: Promote to Production
    needs: [build-and-deploy, e2e-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Promote to Production
        run: npx vercel promote ${{ needs.build-and-deploy.outputs.deployment-url }} --token=${{ secrets.VERCEL_TOKEN }} --yes
